{% set version = "1.4-5" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-adlift
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/adlift_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/adlift/adlift_{{ version }}.tar.gz
  sha256: b3e1ddf1f45ff047fbaed627ae3d9320a0d8c58ccd699f7cab871156fa54c14d

build:
  number: 2
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}        # [not win]
    - {{ stdlib("c") }}          # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ stdlib("m2w64_c") }}          # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-ebayesthresh
  run:
    - r-base
    - r-ebayesthresh

test:
  commands:
    - $R -e "library('adlift')"           # [not win]
    - "\"%R%\" -e \"library('adlift')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=adlift
  license: GPL-2.0-or-later
  summary: Adaptive wavelet lifting transforms for signal denoising using optimal local neighbourhood regression, from Nunes et al. (2006) <doi:10.1007/s11222-006-6560-y>.
  license_family: GPL
  license_file: {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r
