travis:
  secure:
    BINSTAR_TOKEN: hlLyg12RsaBMouCbkDXw3/qiA2ppcf7Um3iMtcSwwz4pODl8PVLr5bIDFzHlXqMeBl9aRkXrg+3qtQ73AzRNKXzc3+rsnwKsTkpwrtjzkrvluHcFVAwEN5C+9TyBjyI63hlRloXhlQyHbw1xm23f6gBpupo62rd9HSyAMgUS2lmB/puM70oX059yy1tROk8Eq6FsF9Mqf8gAW8ZkY0S4M4qfZ/MzDLxoChPBq/oO0eLpmjEkd4nwBJlVl/uc/P7Br0rUSHDj03/cUuCe3p3L/emGxPBd/Rl/gWuTcthsIQb1imu0MqQX3C35ho1eB9cVVlsN5ZfgxsAOML1xs5k/wWzPfd1rF6wUIRD04UGj2EPZwGE4YD9p5XYIa9wSnGetSZdcv8fJ+x+g+CkvG5Qn79MUvXT+KnbuqJaKNaoPB0+pDmp7Fv3U5hYprUILSGCBRtLfkJL72KWTVuzNJv6pR//xuNzd6iVGTW5CKiwZI1WUuDDI2PtZTIwAVkn8BTGA+2NIPoBLBonq3i9c4+htqMx3PNT5+JwavK5ofgJXwvXu0T23MQcX4dpi+xqD4oCcFZkjfsuSer8cH8PfszSQv0ej1HAiH6bswR73fPWHbHa8gGwBfNrEfFAlUU8sbeWoGOTzU89SI9H4WAPTCeV8NBBWpDPsSXz4idDh5diFRfw=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
