appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {win: azure}
travis:
  secure: {BINSTAR_TOKEN: nrDiputzAjY/N9xdaIFCBucT61RBHxGFP9PyDF3mAdcsteLeWj140EXrHGUZOGVMWQLtVyxpLz7KUbmsEjk7tYG0GpyDCtNuM8ApgAmvE7KAQUTUOJuuXuuLzPFaS8wcyayx6/gFqtslcue1hmtfH4blMmNUPBDFLAWIluQrVpzY3i92/iD+t9UiVHB9wlm6zRyoCDIquT+dfhwUYKNe58It85YrIxF7yD3UBdYST94rVX9OtksHntUGdKKQUMGNpyHOo/N8yhH8TTncAYlE0nmVGL8JdcgUloszOTpflie/p0VdP44aFIA3+Gfe/A0gs4h9Q3eCqYUKSK+oCMOw01oeQ4IyAwY4DWc+Smve5CCFNMHm7yIwWM0PS5ozyyex/QrUzBCgJPViM3y7BvMM+J6QudV5RaL8PuYunuX/fgbw+WKOnOn68n+ukmFKXI44i1MFeps8rI7s0XhrFA8Jwo/mCB+NVg3RoCZQNT734wD9hRBGEb0BByyTSVP85SKbMc7tdd+k2SiIg9KzQzwYYecEbUsL/u8HIOBM7iFGqNS7LuLDYoAgxHeKOj6WWEQprhybTyZilTdADSe+utVT2xUOe8HdHafjGNoCbRjpwnSQOqw7JyiWWcy5laV/6qGkn2AfovZvN1x31nLJRWaT4xAI6Me43Mm8/0jQnonMm6I=}
bot:
  automerge: true
